# Generated by Django 5.2 on 2025-04-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
